language:
- objective-c
env:
  global:
  - BUILD_COMMIT='latest-tag'  # comment out to build version in submodule
  - LIBYAML_VERSION=0.1.5
  matrix:
  - VERSION=2.7.9
  - VERSION=3.3.5
  - VERSION=3.4.3
install:
  - source terryfy/travis_tools.sh
  - source terryfy/library_installers.sh
  - clean_builds
  - standard_install yaml $LIBYAML_VERSION
  - get_python_environment macpython $VERSION venv
  - pip install delocate cython
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit pyyaml $BUILD_COMMIT;
    fi
  - source yaml_tools.sh
  - patch_setup_cfg
  - pip wheel -w wheelhouse ./pyyaml
  - delocate-listdeps wheelhouse/*.whl # lists library dependencies
  - delocate-wheel wheelhouse/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 wheelhouse/*.whl
  - pip install wheelhouse/*.whl
script:
  # install dependencies for tests e.g - pip install nose
  # Run the tests
  - python run_tests.py
before_deploy: cd wheelhouse
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: ALZrkCwjz3nY/9GfTNPgVQHUmUpCc5SnZTaqIUlJrhVyOBu6aktXaRmQi+sTXzFn7a/PQsYDnoZ8nibCZ472oUVDGUOSbtjIEkPodU+aisLN2dSLNueQsUU7Dmt0SaeyJVGovzfyUiavIYLuAfOtCfUKrwAsi7XTVNQpdyWCQDs=
  region: ORD
  container: wheels
  skip_cleanup: true
